#ENGINE SETTINGS
CONF_THRESH=0.5
IOU_THRESHOLD=0.4
#COLOR_SETTINGS
MIN_HBLUE = 80
MAX_HBLUE = 120

MIN_HRED1 = 0
MAX_HRED1 = 20
MIN_HRED2 = 165
MAX_HRED2 = 180

RED = 0
BLUE = 1

COLORS = [(255,0,0),(0,0,255)]


#BALL DISTANCE AND SIZE
#CHANGE FOR EACH CAMERA
BALL_F = 653.8
BALL_SIZE = 9.5

WH_RATIO = 2
#CAMERA SETTINGS
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

DISPLAY_IMAGE = True

ENGINE_PATH = "model/exp12.engine"

COLOR_THRESH = 0


#SOCKET VARIABLES
USE_SOCKETS = True

HOST = "10.1.14.2"
PORT = 8888
HOST = "10.220.8.28"

#PLUGIN LIBRARY FOR YOLOV5 ENGINE
#built from https://github.com/wang-xinyu/tensorrtx
PLUGIN_LIBRARY = "build/libmyplugins.so"
